name: Suggest Alternative
description: Suggest a fork or alternative Workflow which can replace another on the list
body:
  - type: input
    attributes:
      label: Original Workflow name
      description: Written as in [the table](https://github.com/alfredapp/updated-third-party-python2-workflows#workflows)
    validations:
      required: true
  - type: input
    attributes:
      label: Alternative Workflow page
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra details
